name: formu
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.0.1+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  liquid_swipe: ^2.1.0
  flutter_zoom_drawer: ^2.3.1+1
  provider: ^6.0.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash:
  flutter_lints: ^2.0.1
  change_app_package_name: ^1.1.0

flutter_native_splash: 
  color: "ffffff"
  image: 'assets/icon/icon.png'
    
flutter_icons: 
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/icon.png'
  adaptive_icon_background: 'assets/icon/icon.png' 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/fondofor.png
    - assets/images/fondo1.png
    - assets/images/fondo2.png
    - assets/images/fondo3.png
    - assets/images/fondo4.png
    - assets/images/fondo5.png
    - assets/images/fondo6.png
    - assets/images/quimica_OxM.png
    - assets/images/quimica_OxNM.png
    - assets/images/quimica_RS.png
    - assets/images/quimica_RC.png
    - assets/images/fisica_C.png
    - assets/images/formula1_f10.png
    - assets/images/formula2_f10.png
    - assets/images/formula3_f10.png
    - assets/images/formula4_f10.png
    - assets/images/formula5_f10.png
    - assets/images/formula6_f10.png
    - assets/images/formula7_f10.png
    - assets/images/formula8_f10.png
    - assets/images/formula9_f10.png
    - assets/images/formula10_f10.png
    - assets/images/formula11_f10.png
    - assets/images/formula12_f10.png
    - assets/images/formula13_f10.png
    - assets/images/formula14_f10.png
    - assets/images/formula15_f10.png
    - assets/images/formula16_f10.png
    - assets/images/formula17_f10.png
    - assets/images/formula18_f10.png
    - assets/images/formula19_f10.png
    - assets/images/formula20_f10.png
    - assets/images/formula21_f10.png
    - assets/images/formula22_f10.png
    - assets/images/formula1_m8.png
    - assets/images/formula2_m8.png
    - assets/images/formula3_m8.png
    - assets/images/formula4_m8.png
    - assets/images/formula5_m8.png
    - assets/images/formula6_m8.png
    - assets/images/formula7_m8.png
    - assets/images/formula8_m8.png
    - assets/images/formula9_m8.png
    - assets/images/formula10_m8.png
    - assets/images/formula11_m8.png
    - assets/images/formula12_m8.png
    - assets/images/formula1_m9.png
    - assets/images/formula2_m9.png
    - assets/images/formula3_m9.png
    - assets/images/formula4_m9.png
    - assets/images/formula5_m9.png
    - assets/images/formula6_m9.png
    - assets/images/formula7_m9.png
    - assets/images/formula8_m9.png
    - assets/images/formula1_m10.png
    - assets/images/formula2_m10.png
    - assets/images/formula3_m10.png
    - assets/images/formula4_m10.png
    - assets/images/formula5_m10.png
    - assets/images/formula6_m10.png
    - assets/images/formula7_m10.png
    - assets/images/formula8_m10.png
    - assets/images/formula9_m10.png
    - assets/images/formula1_f11.png
    - assets/images/formula2_f11.png
    - assets/images/formula3_f11.png
    - assets/images/formula4_f11.png
    - assets/images/formula5_f11.png
    - assets/images/formula6_f11.png
    - assets/images/formula7_f11.png
    - assets/images/formula8_f11.png
    - assets/images/formula9_f11.png
    - assets/images/formula10_f11.png
    - assets/images/formula11_f11.png
    - assets/images/formula12_f11.png
    - assets/images/formula13_f11.png
    - assets/images/formula14_f11.png
    - assets/images/formula15_f11.png
    - assets/images/formula16_f11.png
    - assets/images/formula17_f11.png
    - assets/images/formula18_f11.png
    - assets/images/formula19_f11.png
    - assets/images/formula20_f11.png
    - assets/images/formula21_f11.png
    - assets/images/formula22_f11.png
    - assets/images/formula23_f11.png
    - assets/images/formula24_f11.png
    - assets/images/formula1_m11.png
    - assets/images/formula2_m11.png
    - assets/images/formula3_m11.png
    - assets/images/formula4_m11.png
    - assets/images/formula5_m11.png
    - assets/images/formula6_m11.png
    - assets/images/formula7_m11.png
    - assets/images/formula8_m11.png
    - assets/images/formula9_m11.png
    - assets/images/formula10_m11.png
    - assets/images/formula11_m11.png
    - assets/images/formula12_m11.png
    - assets/images/formula13_m11.png
    - assets/images/formula14_m11.png
    - assets/images/formula15_m11.png
    - assets/images/formula16_m11.png
    - assets/images/formula17_m11.png
    - assets/images/formula18_m11.png
    - assets/images/formula19_m11.png
    - assets/images/formula20_m11.png
    - assets/images/formula21_m11.png
    - assets/images/formula22_m11.png
    - assets/images/formula23_m11.png
    - assets/images/formula24_m11.png
    - assets/images/formula1_m12.png
    - assets/images/formula2_m12.png
    - assets/images/formula3_m12.png
    - assets/images/formula4_m12.png
    - assets/images/formula5_m12.png
    - assets/images/formula6_m12.png
    - assets/images/formula7_m12.png
    - assets/images/formula8_m12.png
    - assets/images/formula9_m12.png
    - assets/images/formula10_m12.png
    - assets/images/formula11_m12.png
    - assets/images/formula12_m12.png
    - assets/images/formula13_m12.png
    - assets/images/formula14_m12.png
    - assets/images/formula15_m12.png
    - assets/images/formula16_m12.png
    - assets/images/formula17_m12.png
    - assets/images/formula18_m12.png
    - assets/images/formula19_m12.png
    - assets/images/formula20_m12.png
    - assets/images/formula21_m12.png
    - assets/images/formula22_m12.png
    - assets/images/formula23_m12.png
    - assets/images/formula24_m12.png
    - assets/images/formula1_m7.png
    - assets/images/formula2_m7.png
    - assets/images/formula3_m7.png
    - assets/images/formula4_m7.png
    - assets/images/formula1_q11.png
    - assets/images/formula2_q11.png
    - assets/images/formula3_q11.png
    - assets/images/formula4_q11.png
    - assets/images/formula5_q11.png
    - assets/images/formula6_q11.png
    - assets/images/formula7_q11.png
    - assets/images/formula8_q11.png
    - assets/images/formula9_q11.png
    - assets/images/formula10_q11.png
    - assets/images/formula11_q11.png
    - assets/images/formula12_q11.png
    - assets/images/formula13_q11.png
    - assets/images/formula1_m7.png
    - assets/images/formula2_m7.png
    - assets/images/formula3_m7.png
    - assets/images/formula4_m7.png
    - assets/images/formula1_q12.png
    - assets/images/formula2_q12.png
    - assets/images/formula3_q12.png
    - assets/images/formula4_q12.png
    - assets/images/formula5_q12.png
    - assets/images/formula6_q12.png
    - assets/images/formula7_q12.png
    - assets/images/formula8_q12.png
    - assets/images/formula9_q12.png
    - assets/images/formula10_q12.png
    - assets/images/formula11_q12.png
    - assets/images/formula12_q12.png
    - assets/images/formula13_q12.png
    - assets/images/formula14_q12.png
    - assets/images/formula15_q12.png
    - assets/images/formula16_q12.png
    - assets/icon/longitud.png
    - assets/icon/masa.png
    - assets/icon/volumen.png
    - assets/icon/tiempo.png
    - assets/icon/velocidad.png
    - assets/icon/temperatura.png
    - assets/icon/prueba1.png
    - assets/icon/perfil.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
