// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaginaCole.Models;

namespace PaginaCole.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20220905182817_db_cole")]
    partial class db_cole
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("PaginaCole.Models.HorarioDiario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Fecha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("HorariosDi");
                });

            modelBuilder.Entity("PaginaCole.Models.HorarioSeccion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seccion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("HorariosSe");
                });

            modelBuilder.Entity("PaginaCole.Models.Horarios", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("DId")
                        .HasColumnType("int");

                    b.Property<int>("SId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DId");

                    b.HasIndex("SId");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("PaginaCole.Models.Horarios", b =>
                {
                    b.HasOne("PaginaCole.Models.HorarioDiario", "D")
                        .WithMany()
                        .HasForeignKey("DId");

                    b.HasOne("PaginaCole.Models.HorarioSeccion", "S")
                        .WithMany()
                        .HasForeignKey("SId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("D");

                    b.Navigation("S");
                });
#pragma warning restore 612, 618
        }
    }
}
